# Generated by Django 2.0.2 on 2018-05-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('b_date', models.DateTimeField()),
                ('address', models.CharField(max_length=15)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Education')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Phone'),
        ),
    ]
